// 12 preset themes — 6 accent color pairs, each with a dark and light variant.
// Variable names mirror the CSS custom properties in styles.css.
// `dark: true` drives the body.light class toggle for tag/badge color overrides.

export const themes = [
  {
    id: 'ember-dark',
    label: 'Ember',
    dark: true,
    vars: {
      '--bg':         '#0f0b09',
      '--surface':    '#141414',
      '--panel':      '#212121',
      '--border':     '#282828',
      '--border-hi':  '#3a3a3a',
      '--text':       '#e8e8e8',
      '--muted':      '#666',
      '--muted-hi':   '#999',
      '--orange':     '#e86807',
      '--orange-dim': '#e8680722',
      '--orange-hi':  '#ff8c38',
      '--ok':         '#4ade80',
      '--fail':       '#f87171',
      '--warn':       '#fbbf24',
    },
  },
  {
    id: 'ember-light',
    label: 'Ember',
    dark: false,
    vars: {
      '--bg':         '#f4f4f4',
      '--surface':    '#ebebeb',
      '--panel':      '#e2e2e2',
      '--border':     '#d0d0d0',
      '--border-hi':  '#b8b8b8',
      '--text':       '#1a1a1a',
      '--muted':      '#777',
      '--muted-hi':   '#444',
      '--orange':     '#d05d06',
      '--orange-dim': '#d05d0618',
      '--orange-hi':  '#f97316',
      '--ok':         '#16a34a',
      '--fail':       '#dc2626',
      '--warn':       '#d97706',
    },
  },
  {
    id: 'teal-dark',
    label: 'Teal',
    dark: true,
    vars: {
      '--bg':         '#080f0e',
      '--surface':    '#0f1a19',
      '--panel':      '#192825',
      '--border':     '#1e302d',
      '--border-hi':  '#2e4a46',
      '--text':       '#e8e8e8',
      '--muted':      '#666',
      '--muted-hi':   '#999',
      '--orange':     '#0d9488',
      '--orange-dim': '#0d948822',
      '--orange-hi':  '#2dd4bf',
      '--ok':         '#4ade80',
      '--fail':       '#f87171',
      '--warn':       '#fbbf24',
    },
  },
  {
    id: 'teal-light',
    label: 'Teal',
    dark: false,
    vars: {
      '--bg':         '#f0faf9',
      '--surface':    '#e3f5f3',
      '--panel':      '#d5eeec',
      '--border':     '#b8deda',
      '--border-hi':  '#90cac4',
      '--text':       '#1a1a1a',
      '--muted':      '#777',
      '--muted-hi':   '#444',
      '--orange':     '#0d7a70',
      '--orange-dim': '#0d7a7018',
      '--orange-hi':  '#0d9488',
      '--ok':         '#16a34a',
      '--fail':       '#dc2626',
      '--warn':       '#d97706',
    },
  },
  {
    id: 'iris-dark',
    label: 'Iris',
    dark: true,
    vars: {
      '--bg':         '#0c0b12',
      '--surface':    '#13111f',
      '--panel':      '#1e1b2e',
      '--border':     '#282540',
      '--border-hi':  '#3a3758',
      '--text':       '#e8e8e8',
      '--muted':      '#666',
      '--muted-hi':   '#999',
      '--orange':     '#7c3aed',
      '--orange-dim': '#7c3aed22',
      '--orange-hi':  '#a78bfa',
      '--ok':         '#4ade80',
      '--fail':       '#f87171',
      '--warn':       '#fbbf24',
    },
  },
  {
    id: 'iris-light',
    label: 'Iris',
    dark: false,
    vars: {
      '--bg':         '#faf5ff',
      '--surface':    '#f0e8ff',
      '--panel':      '#e8d8ff',
      '--border':     '#c9b5f5',
      '--border-hi':  '#ac98e8',
      '--text':       '#1a1a1a',
      '--muted':      '#777',
      '--muted-hi':   '#444',
      '--orange':     '#6521c8',
      '--orange-dim': '#6521c818',
      '--orange-hi':  '#7c3aed',
      '--ok':         '#16a34a',
      '--fail':       '#dc2626',
      '--warn':       '#d97706',
    },
  },
  {
    id: 'cobalt-dark',
    label: 'Cobalt',
    dark: true,
    vars: {
      '--bg':         '#090c12',
      '--surface':    '#101521',
      '--panel':      '#192030',
      '--border':     '#222f3e',
      '--border-hi':  '#324558',
      '--text':       '#e8e8e8',
      '--muted':      '#666',
      '--muted-hi':   '#999',
      '--orange':     '#2563eb',
      '--orange-dim': '#2563eb22',
      '--orange-hi':  '#60a5fa',
      '--ok':         '#4ade80',
      '--fail':       '#f87171',
      '--warn':       '#fbbf24',
    },
  },
  {
    id: 'cobalt-light',
    label: 'Cobalt',
    dark: false,
    vars: {
      '--bg':         '#eff6ff',
      '--surface':    '#e1edff',
      '--panel':      '#d4e5ff',
      '--border':     '#b8d4f5',
      '--border-hi':  '#95bde8',
      '--text':       '#1a1a1a',
      '--muted':      '#777',
      '--muted-hi':   '#444',
      '--orange':     '#1d4ed8',
      '--orange-dim': '#1d4ed818',
      '--orange-hi':  '#2563eb',
      '--ok':         '#16a34a',
      '--fail':       '#dc2626',
      '--warn':       '#d97706',
    },
  },
  {
    id: 'sage-dark',
    label: 'Sage',
    dark: true,
    vars: {
      '--bg':         '#090f0b',
      '--surface':    '#101a12',
      '--panel':      '#192818',
      '--border':     '#22342a',
      '--border-hi':  '#334e3e',
      '--text':       '#e8e8e8',
      '--muted':      '#666',
      '--muted-hi':   '#999',
      '--orange':     '#16a34a',
      '--orange-dim': '#16a34a22',
      '--orange-hi':  '#4ade80',
      '--ok':         '#4ade80',
      '--fail':       '#f87171',
      '--warn':       '#fbbf24',
    },
  },
  {
    id: 'sage-light',
    label: 'Sage',
    dark: false,
    vars: {
      '--bg':         '#f0fdf4',
      '--surface':    '#e3f9e8',
      '--panel':      '#d5f5de',
      '--border':     '#b8e8c5',
      '--border-hi':  '#8dcca0',
      '--text':       '#1a1a1a',
      '--muted':      '#777',
      '--muted-hi':   '#444',
      '--orange':     '#15803d',
      '--orange-dim': '#15803d18',
      '--orange-hi':  '#16a34a',
      '--ok':         '#16a34a',
      '--fail':       '#dc2626',
      '--warn':       '#d97706',
    },
  },
  {
    id: 'rose-dark',
    label: 'Rose',
    dark: true,
    vars: {
      '--bg':         '#110a0e',
      '--surface':    '#1c1018',
      '--panel':      '#281820',
      '--border':     '#361f2c',
      '--border-hi':  '#4e3040',
      '--text':       '#e8e8e8',
      '--muted':      '#666',
      '--muted-hi':   '#999',
      '--orange':     '#e11d74',
      '--orange-dim': '#e11d7422',
      '--orange-hi':  '#f472b6',
      '--ok':         '#4ade80',
      '--fail':       '#f87171',
      '--warn':       '#fbbf24',
    },
  },
  {
    id: 'rose-light',
    label: 'Rose',
    dark: false,
    vars: {
      '--bg':         '#fff0f6',
      '--surface':    '#fce0ed',
      '--panel':      '#f8d0e4',
      '--border':     '#f0b0cf',
      '--border-hi':  '#e090b8',
      '--text':       '#1a1a1a',
      '--muted':      '#777',
      '--muted-hi':   '#444',
      '--orange':     '#9d1455',
      '--orange-dim': '#9d145518',
      '--orange-hi':  '#be185d',
      '--ok':         '#16a34a',
      '--fail':       '#dc2626',
      '--warn':       '#d97706',
    },
  },
]

export const themeMap = Object.fromEntries(themes.map(t => [t.id, t]))

// Default font stacks offered in the settings font selector.
export const sansFonts  = ['Inter', 'Segoe UI', 'system-ui', 'Open Sans', 'Helvetica Neue']
export const monoFonts  = ['JetBrains Mono', 'Fira Code', 'Consolas', 'Source Code Pro', 'Cascadia Code']

// Apply a theme to the document. Sets all CSS custom properties on :root and
// toggles `body.light` so legacy selectors in styles.css (tag colors, etc.) keep working.
export function applyTheme(themeId, fontSans, fontMono) {
  const theme = themeMap[themeId] ?? themeMap['ember-dark']
  const root = document.documentElement
  for (const [k, v] of Object.entries(theme.vars)) {
    root.style.setProperty(k, v)
  }
  if (fontSans) root.style.setProperty('--sans', `'${fontSans}', system-ui, sans-serif`)
  if (fontMono) root.style.setProperty('--mono', `'${fontMono}', 'Fira Code', monospace`)
  document.body.classList.toggle('light', !theme.dark)
}
